// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////

#include "ui_MainScreen.h"
#include "ui_MenuScreen.h"
#include "ui_LaserScreen.h"
#include "ui_GyroScreen.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// FONTS
LV_FONT_DECLARE(ui_font_FontHour1000);
LV_FONT_DECLARE(ui_font_FontHour10000);
LV_FONT_DECLARE(ui_font_FontHour100000);
LV_FONT_DECLARE(ui_font_FontMin100);
LV_FONT_DECLARE(ui_font_FontMin10000);
LV_FONT_DECLARE(ui_font_FontMin100000);
LV_FONT_DECLARE(ui_font_FontMin5);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
