// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_GyroScreen = NULL;
lv_obj_t * ui_XLabel = NULL;
lv_obj_t * ui_YLabel = NULL;
lv_obj_t * ui_ZLabel = NULL;
lv_obj_t * ui_YBar = NULL;
lv_obj_t * ui_XBar = NULL;
lv_obj_t * ui_ZBar = NULL;
lv_obj_t * ui_SleepArcGyro = NULL;
// event funtions

// build funtions

void ui_GyroScreen_screen_init(void)
{
    ui_GyroScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_GyroScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_XLabel = lv_label_create(ui_GyroScreen);
    lv_obj_set_width(ui_XLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_XLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_XLabel, 160);
    lv_obj_set_y(ui_XLabel, 95);
    lv_label_set_text(ui_XLabel, "X%");
    lv_obj_set_style_text_color(ui_XLabel, lv_color_hex(0x81A684), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_XLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_XLabel, &ui_font_FontMin100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_YLabel = lv_label_create(ui_GyroScreen);
    lv_obj_set_width(ui_YLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_YLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_YLabel, 160);
    lv_obj_set_y(ui_YLabel, -5);
    lv_obj_set_align(ui_YLabel, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_YLabel, "Y%");
    lv_obj_set_style_text_color(ui_YLabel, lv_color_hex(0x57886C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_YLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_YLabel, &ui_font_FontMin100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ZLabel = lv_label_create(ui_GyroScreen);
    lv_obj_set_width(ui_ZLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ZLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ZLabel, 160);
    lv_obj_set_y(ui_ZLabel, -100);
    lv_obj_set_align(ui_ZLabel, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_ZLabel, "Z%");
    lv_obj_set_style_text_color(ui_ZLabel, lv_color_hex(0x466060), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_ZLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_ZLabel, &ui_font_FontMin100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_YBar = lv_bar_create(ui_GyroScreen);
    lv_bar_set_range(ui_YBar, -180, 180);
    lv_obj_set_width(ui_YBar, 150);
    lv_obj_set_height(ui_YBar, 10);
    lv_obj_set_x(ui_YBar, 5);
    lv_obj_set_y(ui_YBar, 0);
    lv_obj_set_align(ui_YBar, LV_ALIGN_LEFT_MID);
    lv_obj_set_style_bg_color(ui_YBar, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_YBar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_YBar, lv_color_hex(0x57886C), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_YBar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_XBar = lv_bar_create(ui_GyroScreen);
    lv_bar_set_range(ui_XBar, -180, 180);
    lv_obj_set_width(ui_XBar, 150);
    lv_obj_set_height(ui_XBar, 10);
    lv_obj_set_x(ui_XBar, 5);
    lv_obj_set_y(ui_XBar, 100);
    lv_obj_set_style_bg_color(ui_XBar, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_XBar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_XBar, lv_color_hex(0x81A684), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_XBar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_ZBar = lv_bar_create(ui_GyroScreen);
    lv_bar_set_range(ui_ZBar, -180, 180);
    lv_obj_set_width(ui_ZBar, 150);
    lv_obj_set_height(ui_ZBar, 10);
    lv_obj_set_x(ui_ZBar, 5);
    lv_obj_set_y(ui_ZBar, -100);
    lv_obj_set_align(ui_ZBar, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_set_style_bg_color(ui_ZBar, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ZBar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_ZBar, lv_color_hex(0x466060), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ZBar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_SleepArcGyro = lv_arc_create(ui_GyroScreen);
    lv_obj_set_width(ui_SleepArcGyro, lv_pct(20));
    lv_obj_set_height(ui_SleepArcGyro, lv_pct(20));
    lv_obj_set_x(ui_SleepArcGyro, -3);
    lv_obj_set_y(ui_SleepArcGyro, 30);
    lv_obj_set_align(ui_SleepArcGyro, LV_ALIGN_TOP_RIGHT);
    lv_arc_set_value(ui_SleepArcGyro, 0);
    lv_arc_set_bg_angles(ui_SleepArcGyro, 90, 89);
    lv_obj_set_style_arc_color(ui_SleepArcGyro, lv_color_hex(0x4040FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_SleepArcGyro, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_SleepArcGyro, lv_color_hex(0xFF6262), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_SleepArcGyro, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_SleepArcGyro, 4, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SleepArcGyro, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SleepArcGyro, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

}

void ui_GyroScreen_screen_destroy(void)
{
    if(ui_GyroScreen) lv_obj_del(ui_GyroScreen);

    // NULL screen variables
    ui_GyroScreen = NULL;
    ui_XLabel = NULL;
    ui_YLabel = NULL;
    ui_ZLabel = NULL;
    ui_YBar = NULL;
    ui_XBar = NULL;
    ui_ZBar = NULL;
    ui_SleepArcGyro = NULL;

}
