// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_GYROSCREEN_H
#define UI_GYROSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_GyroScreen
extern void ui_GyroScreen_screen_init(void);
extern void ui_GyroScreen_screen_destroy(void);
extern lv_obj_t * ui_GyroScreen;
extern lv_obj_t * ui_XLabel;
extern lv_obj_t * ui_YLabel;
extern lv_obj_t * ui_ZLabel;
extern lv_obj_t * ui_YBar;
extern lv_obj_t * ui_XBar;
extern lv_obj_t * ui_ZBar;
extern lv_obj_t * ui_SleepArcGyro;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

