// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_LASERSCREEN_H
#define UI_LASERSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_LaserScreen
extern void ui_LaserScreen_screen_init(void);
extern void ui_LaserScreen_screen_destroy(void);
extern lv_obj_t * ui_LaserScreen;
extern lv_obj_t * ui_LaserSwitch;
extern lv_obj_t * ui_SleepArcLaser;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

