// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_LaserScreen = NULL;
lv_obj_t * ui_LaserSwitch = NULL;
lv_obj_t * ui_SleepArcLaser = NULL;
// event funtions

// build funtions

void ui_LaserScreen_screen_init(void)
{
    ui_LaserScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_LaserScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LaserSwitch = lv_switch_create(ui_LaserScreen);
    lv_obj_set_width(ui_LaserSwitch, 171);
    lv_obj_set_height(ui_LaserSwitch, 80);
    lv_obj_set_align(ui_LaserSwitch, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_LaserSwitch, lv_color_hex(0x57886C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LaserSwitch, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_LaserSwitch, lv_color_hex(0x466060), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_LaserSwitch, 255, LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_color(ui_LaserSwitch, lv_color_hex(0x466060), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_LaserSwitch, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_SleepArcLaser = lv_arc_create(ui_LaserScreen);
    lv_obj_set_width(ui_SleepArcLaser, lv_pct(20));
    lv_obj_set_height(ui_SleepArcLaser, lv_pct(20));
    lv_obj_set_x(ui_SleepArcLaser, -3);
    lv_obj_set_y(ui_SleepArcLaser, 30);
    lv_obj_set_align(ui_SleepArcLaser, LV_ALIGN_TOP_RIGHT);
    lv_arc_set_value(ui_SleepArcLaser, 0);
    lv_arc_set_bg_angles(ui_SleepArcLaser, 90, 89);
    lv_obj_set_style_arc_color(ui_SleepArcLaser, lv_color_hex(0x4040FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_SleepArcLaser, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_SleepArcLaser, lv_color_hex(0xFF6262), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_SleepArcLaser, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_SleepArcLaser, 4, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SleepArcLaser, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SleepArcLaser, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

}

void ui_LaserScreen_screen_destroy(void)
{
    if(ui_LaserScreen) lv_obj_del(ui_LaserScreen);

    // NULL screen variables
    ui_LaserScreen = NULL;
    ui_LaserSwitch = NULL;
    ui_SleepArcLaser = NULL;

}
