// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_MenuScreen = NULL;
lv_obj_t * ui_UiMenuRoller = NULL;
// event funtions

// build funtions

void ui_MenuScreen_screen_init(void)
{
    ui_MenuScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_MenuScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_UiMenuRoller = lv_roller_create(ui_MenuScreen);
    lv_roller_set_options(ui_UiMenuRoller, "Time\nLevel\nLaser\nFitness", LV_ROLLER_MODE_INFINITE);
    lv_obj_set_height(ui_UiMenuRoller, 252);
    lv_obj_set_width(ui_UiMenuRoller, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_align(ui_UiMenuRoller, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_UiMenuRoller, lv_color_hex(0x466060), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_UiMenuRoller, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_UiMenuRoller, &ui_font_FontMin5, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_UiMenuRoller, lv_color_hex(0x81A684), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_UiMenuRoller, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);

}

void ui_MenuScreen_screen_destroy(void)
{
    if(ui_MenuScreen) lv_obj_del(ui_MenuScreen);

    // NULL screen variables
    ui_MenuScreen = NULL;
    ui_UiMenuRoller = NULL;

}
