// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_MainScreen = NULL;
lv_obj_t * ui_UiHourLabel = NULL;
lv_obj_t * ui_UiMinLabel = NULL;
lv_obj_t * ui_UiBatBar = NULL;
lv_obj_t * ui_UiBatLabel = NULL;
lv_obj_t * ui_StepsArc = NULL;
lv_obj_t * ui_StepsLabel = NULL;
lv_obj_t * ui_SleepArcMain = NULL;
// event funtions

// build funtions

void ui_MainScreen_screen_init(void)
{
    ui_MainScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_MainScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_font(ui_MainScreen, &ui_font_FontMin10000, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_UiHourLabel = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_UiHourLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_UiHourLabel, LV_SIZE_CONTENT);    /// 1
    lv_label_set_text(ui_UiHourLabel, "00");
    lv_obj_set_style_text_color(ui_UiHourLabel, lv_color_hex(0x81A684), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_UiHourLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_UiHourLabel, &ui_font_FontMin100000, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_UiMinLabel = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_UiMinLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_UiMinLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_UiMinLabel, 0);
    lv_obj_set_y(ui_UiMinLabel, 50);
    lv_obj_set_align(ui_UiMinLabel, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_UiMinLabel, "00");
    lv_obj_set_style_text_color(ui_UiMinLabel, lv_color_hex(0x57886C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_UiMinLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_UiMinLabel, &ui_font_FontMin10000, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_UiBatBar = lv_bar_create(ui_MainScreen);
    lv_bar_set_value(ui_UiBatBar, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_UiBatBar, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_UiBatBar, 80);
    lv_obj_set_height(ui_UiBatBar, 10);
    lv_obj_set_x(ui_UiBatBar, -63);
    lv_obj_set_y(ui_UiBatBar, -114);
    lv_obj_set_align(ui_UiBatBar, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_UiBatBar, lv_color_hex(0xDADADA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_UiBatBar, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_UiBatBar, lv_color_hex(0x466060), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_UiBatBar, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_UiBatLabel = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_UiBatLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_UiBatLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_UiBatLabel, 2);
    lv_obj_set_y(ui_UiBatLabel, -117);
    lv_obj_set_align(ui_UiBatLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_UiBatLabel, "25%");
    lv_obj_set_style_text_color(ui_UiBatLabel, lv_color_hex(0x466060), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_UiBatLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_UiBatLabel, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_UiBatLabel, &ui_font_FontMin100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StepsArc = lv_arc_create(ui_MainScreen);
    lv_obj_set_width(ui_StepsArc, 70);
    lv_obj_set_height(ui_StepsArc, 150);
    lv_obj_set_x(ui_StepsArc, 10);
    lv_obj_set_y(ui_StepsArc, 40);
    lv_obj_set_align(ui_StepsArc, LV_ALIGN_BOTTOM_LEFT);
    lv_arc_set_value(ui_StepsArc, 0);
    lv_arc_set_bg_angles(ui_StepsArc, 90, 89);
    lv_obj_set_style_arc_color(ui_StepsArc, lv_color_hex(0x4040FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_StepsArc, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_StepsArc, lv_color_hex(0x466060), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_StepsArc, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_StepsArc, lv_color_hex(0x466060), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_StepsArc, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_StepsLabel = lv_label_create(ui_MainScreen);
    lv_obj_set_width(ui_StepsLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_StepsLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_StepsLabel, 17);
    lv_obj_set_y(ui_StepsLabel, -25);
    lv_obj_set_align(ui_StepsLabel, LV_ALIGN_BOTTOM_LEFT);
    lv_label_set_text(ui_StepsLabel, "10000");
    lv_obj_set_style_text_color(ui_StepsLabel, lv_color_hex(0x466060), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_StepsLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_StepsLabel, &ui_font_FontMin100, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SleepArcMain = lv_arc_create(ui_MainScreen);
    lv_obj_set_width(ui_SleepArcMain, lv_pct(20));
    lv_obj_set_height(ui_SleepArcMain, lv_pct(20));
    lv_obj_set_x(ui_SleepArcMain, -3);
    lv_obj_set_y(ui_SleepArcMain, 30);
    lv_obj_set_align(ui_SleepArcMain, LV_ALIGN_TOP_RIGHT);
    lv_arc_set_value(ui_SleepArcMain, 0);
    lv_arc_set_bg_angles(ui_SleepArcMain, 90, 89);
    lv_obj_set_style_arc_color(ui_SleepArcMain, lv_color_hex(0x4040FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_SleepArcMain, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_SleepArcMain, lv_color_hex(0xFF6262), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_SleepArcMain, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_SleepArcMain, 4, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_SleepArcMain, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SleepArcMain, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

}

void ui_MainScreen_screen_destroy(void)
{
    if(ui_MainScreen) lv_obj_del(ui_MainScreen);

    // NULL screen variables
    ui_MainScreen = NULL;
    ui_UiHourLabel = NULL;
    ui_UiMinLabel = NULL;
    ui_UiBatBar = NULL;
    ui_UiBatLabel = NULL;
    ui_StepsArc = NULL;
    ui_StepsLabel = NULL;
    ui_SleepArcMain = NULL;

}
