// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_MAINSCREEN_H
#define UI_MAINSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_MainScreen
extern void ui_MainScreen_screen_init(void);
extern void ui_MainScreen_screen_destroy(void);
extern lv_obj_t * ui_MainScreen;
extern lv_obj_t * ui_UiHourLabel;
extern lv_obj_t * ui_UiMinLabel;
extern lv_obj_t * ui_UiBatBar;
extern lv_obj_t * ui_UiBatLabel;
extern lv_obj_t * ui_StepsArc;
extern lv_obj_t * ui_StepsLabel;
extern lv_obj_t * ui_SleepArcMain;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

